### ISSUE TITLE
Add Tatsu Layout to theme

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#10]
I'm not sure if this is the best way to handle this. However, I wanted to provide color module support for a layout with multiple hero regions. 

I could simply offer this layout on it's own in contrib, but since I've added color support for regions contained, I've decided to try and add the layout to the theme. 

Please, provide feedback if this is a bad idea.

**Comment by stpaultim** [comment]
OK, I suppose it should have been obvious, but it doesn't work to simply add a layout to a theme. Maybe I have to release it as contrib and simply recommend that users download it.

**Comment by stpaultim** [comment]
For now, I decided to leave the layout in the theme with instructions to move it to the layouts folder.

**Comment by stpaultim** [comment]
@klonos asked in Gitter:

> I'm also interested to know why choose to include the Tatsu layout as a subfolder within the theme, instead of creating a separate layout project, and then make the layout and the theme depend on each other (via dependencies[] in their .info files)?

I agree that this might be better. @jenlampton suggests:

> depending on region names, you could override the templates for (some of the?) the core layouts. I do that with some of my themes - take over the “top” region for a hero on all layouts.

I'm not sure if this solves the problem I'm trying to solve. I'll try to define the problem better, so that I can get good feedback on the best solution (coming later).

**Comment by docwilmot** [comment]
My thought about this is that Backdrop actively sought to completely separate the concept of page template from site appearance/skin/theme by creating Layout module in core and removing `page.tpl.php`. Starting to merge layouts back into themes defeats this intent. If we merge flexible layouts into core this will be even more so as users will be able to define all sorts of site architecture and expect them to work, not just one or two chosen template included in a theme package. 

What themes should be doing is adding CSS to support as many available layout templates and core/contrib blocks as possible, with disclaimers if necessary, like "Tested/works with core and Hero layouts", or "Works with the Custom Header Block", for example. And leave it to users to choose which template they want to use.

My 2c.

**Comment by jenlampton** [comment]
Overriding the template files is also a good idea so you can get the same markup across all core layouts. I have several themes the support all 10 core layouts, and override all 10 tpl.phps.

**Comment by docwilmot** [comment]
Thats different though. On a custom project, by all means. But if its in contrib, a theme might be paired with any layout.

**Comment by jenlampton** [comment]
Right, which is why my contrib themes need to override all 10. On a custom project I only need one or two. 

I believe *all* contrib themes need to support all 10 core layouts -- and if I ever see one that only overrides one or two layout template files, I'll open an issue :)

**Comment by stpaultim** [comment]
@docwilmot - Thanks for input. I share the concern about tying layouts to themes. I'm new to the contrib theme space and grappling to figure out the best way to accomplish some things and really appreciate this discussion. Hopefully, my fresh eyes in contrib theme space will uncover some possible things we can do with Backdrop to better support contrib themes.

My original use case for the new template was the desire to provide users with multiple `hero` regions in which they could use the color module to give each hero region it's own custom background color. It's clear, my solution was not great, but it was a start. Since then, @hosef has shared work he did on [configurable block styles](https://github.com/hosef/configurable_block_style) module. This might accomplish my goal better and would work with any `hero` theme.

My next challenge in terms of layouts is that none of the existing core or contrib themes has a multi-column footer. 

It might be that the best solution will be to release a new layout as it's own project and simply recommend (or even make it a dependency if that is possible). 

I do plan to make sure that Tatsu supports other layouts. So, I have no intention of building a theme that will only work with a specific layout. I just want users of Tatsu to have additional options that existing layouts do not provide and am trying to figure out the best way to accomplish this.

I am still struggling a bit to understand the implications of @jenlampton suggestion of overriding templates. Is that really an option for something like providing additional columns in the footer of a layout? Is it a user friendly option?

**Comment by stpaultim** [comment]
I should add, that flexible layouts in core might solve many of the problems I'm running into. Certainly it has the potential to resolve the problem of adding columns to the footer. I should experiment with your (@docwilmot) flexible layout PR and Tatsu together.

**Comment by jenlampton** [comment]
> I am still struggling a bit to understand the implications of @jenlampton suggestion of overriding templates. Is that really an option for something like providing additional columns in the footer of a layout? 

No no no no don't do that. :)  edit: please see next comment!

> My original use case for the new template was the desire to provide users with multiple hero regions

If you're getting into adding / removing / renaming regions - that's something that cannot and should not be done in a theme, and needs a layout project.  

Think of it like this: What could you change by **overriding** the `page.tpl.php` file in your Drupal 7 theme? What are the differences between that file, and all the variants like `page--front.tpl.php`, `page--node.tpl.php`, `page--node--1234.tpl.php`, etc?

You couldn't change anything about the regions themselves from one copy to another, but you could control everything around them. You can change where they are on the page, what classes they have, how many wrapper divs they have, etc, but you can't change how many regions there are. 

Since the `page.tpl.php` in D7 "translates" to `layout.tpl.php` in B, it functions exactly the same way -- just don't think about the .info files, that's what throws people off.

**Comment by jenlampton** [comment]
Here's a suitable use-case for overriding layout template files in your theme: 

When you have an equal number of columns in the middle of the page, you want to add an extra gutter around the whole section columns, to make it appear more like the columns are floating in the middle of the page.

Here are screenshots of Sutro and Geary old vs new (please excuse my poor design skills - adjusted regions in red)

![geary](https://user-images.githubusercontent.com/397895/61583937-42256580-aaf4-11e9-8436-27ad4cb1ad03.png)
<img width="60" alt="geary-up" src="https://user-images.githubusercontent.com/397895/61583965-aba57400-aaf4-11e9-8171-0395190b23ed.png">

![sutro](https://user-images.githubusercontent.com/397895/61583940-51a4ae80-aaf4-11e9-8e63-11f702ffa7b1.png)
<img width="62" alt="sutro-up" src="https://user-images.githubusercontent.com/397895/61583959-a0524880-aaf4-11e9-98f9-18c223b90d18.png">

I also often move things like the messages, tabs, and page title etc to a more suitable location for my theme, but those don't show up in the wireframe images :)

**Comment by stpaultim** [comment]
@jenlampton - Good, thanks for clarifications. They support my gut instinct. I think I'm leaning towards creating my own contrib layout which I would recommend but not require for Tatsu.

**Comment by stpaultim** [comment]
Flexible Layout Templates are now in core and provides me with the main thing I was looking for in my custom templates. 

I think we do away with the need for a specific template altogether now.
