### ISSUE TITLE
Provide support for slideshow or carousels

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#26]
Creating this ticket in response to a question in the forum. 
https://forum.backdropcms.org/forum/theme-built-slideshowcarousel-function

First step is to determine what it would mean for Tatsu to support a slideshow or carousel? Does that mean building the entire functionality into Tatsu or simply making sure that Tatsu works with an already existing module?

**Comment by izmeez** [comment]
I would have thought a slideshow would be a module was placed in a layout block, maybe even the hero block for some cases. It might need some additional css. Other than that, not sure why it would be theme specific.

**Comment by stpaultim** [comment]
I'm not certain of the right approach here. But, the reason would be that whatever CSS comes with the slideshow might not be consistent with the theme. 

On the other hand, maybe the necessary theming should be generic enough that it does not require any special theming. In Drupal 7 world, sometimes a theme included some support for a specific module. That might be the case here. 

For now, I think I'll close this issue until there is a more specific use case.

**Comment by Wylbur** [comment]
Perhaps we can see how the Views Slideshow appears when using Tatsu.  This seems to be the most approachable slideshow for Backdrop at the moment.  

We can revisit this if there are requests for that.
