### ISSUE TITLE
Create a logo for Tatsu

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#38]
Maybe I'm getting ahead of the curve, but I'd love to have a custom logo for Tatsu. Maybe some Dragon related as that is how we came to the name Tatsu. It's named after a Dragon. There is also a Six Flags roller coaster with the same name. 

> "The modern Japanese language has numerous "dragon" words, including indigenous **Tatsu** from Old Japanese ta-tu, Sino-Japanese ryū or ryō 竜 from Chinese lóng 龍, nāga ナーガ from Sanskrit nāga, and doragon ドラゴン from English "dragon" (the latter being used almost exclusively to refer to the European dragon and derived fictional creatures)."

https://en.wikipedia.org/wiki/Japanese_dragon

Maybe we could use this for inspiration, it must be in the public domain. Just posting this in case anyone else is inspired.

**Comment by izmeez** [comment]
This is a great idea. A single character dragon would be nice as an example of a logo with site name (theme name) much like zen had.

**Comment by Wylbur** [comment]
How about this image?  Creative Commons Open Source license.
![tatsu](https://github.com/backdrop-contrib/tatsu/assets/238274/a64f57d0-96c1-426b-afe7-c45e7f73cf70)
![tatsu](https://github.com/backdrop-contrib/tatsu/assets/238274/fbbaecff-a64f-4460-b121-3f0e8b2e39ee)

**Comment by stpaultim** [comment]
@Wylbur Sure, I'd be happy with this.

**Comment by stpaultim** [comment]
Merged

**Comment by stpaultim** [comment]
Should we credit the logo in the README.md file? @Wylbur

**Comment by Wylbur** [comment]
It's a Creative Commons Open Source license, so no credit is required.

**Comment by stpaultim** [comment]
Even if not required, I like to put a reference to where I got the image to demonstrate that it is Creative Commons.
