### ISSUE TITLE
Add color module support for changing "hover" color on links

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#39]
I don't think that you can change the hover color of links yet through color module support. I'd like to add that feature. Currently the hover color is not working well on my own site http://www.triplo.co and our goal is to not make any customizations to the CSS other than what we add back to the contrib theme.

**Comment by yorkshire-pudding** [comment]
This is quite an annoyance out of the box.  When links go blue on hover and the background is dark they disappear. Works better in 1.2 (see #57)

**Comment by oadaeh** [comment]
I submitted a PR for this. Please read the comments, as you'll likely have to make changes.
