### ISSUE TITLE
Cut ties with Basis - make Tatsu it's own theme

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#50]
In issue #18 I decided to make Tatsu a sub-theme of Basis, based in part on encouragement from others. The idea was that Tatsu could inherit improvements and bug fixes from Basis. 

Current work/experimentation with color module, makes me think we are making significant enough changes to Tatsu from Basis that the drawbacks of being a sub-theme may outweigh the benefits.

**Comment by Wylbur** [comment]
The latest dev branch cuts ties with Basis, there is no base_theme installed.  Marking this as completed!
