### ISSUE TITLE
Allow custom css via user interface

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#54]
Inspired by this experimental feature in Pelerine theme. 
https://github.com/backdrop-contrib/pelerine/issues/5

Any feedback on this?

**Comment by yorkshire-pudding** [comment]
Works very well in 1.2 - saved me having to make a subtheme

**Comment by izmeez** [comment]
Tried to use this to add a background image with the theme settings page advanced additional css. It's not clear what is meant by choosing a color to add it to the place in your code and not sure where the root for this additional css is.

`body {
  background-image: url(../images/maze-bkgnd-small.png);
  background-repeat: repeat;
}`

**Comment by izmeez** [comment]
Answered my own question. The path needs to be the full path from the document/web root:

`body {
  background-image: url(/themes/tatsu-1.x-2.x/images/maze-bkgnd-small.png);
  background-repeat: repeat; }`

**Comment by izmeez** [comment]
This is a useful feature.

**Comment by Wylbur** [comment]
This feature is now available in the 1.2 branch.  
I also see two comments that is working as expected. 

Closing this as completed.

**Comment by Wylbur** [comment]
Really!
