### ISSUE TITLE
Color module notification

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/tatsu#56]
In 1.19.4 the color module notification got some attention -- Tatsu may need some slight tweaking on the Tatsu settings page when the Color module is not enabled (to avoid duplicated messages). See:

 - https://github.com/backdrop/backdrop-issues/issues/3458

**Comment by Wylbur** [comment]
Testing
- I enabled and disabled the color module with active color modifications present - no errors
- Tatsu settings page simply showed the color options or removed them.  
- Saving the settings page in either state also did not generate errors

Does this task still need action?

**Comment by laryn** [comment]
If you've tested and all looks good, I think we can close this!
