### ISSUE TITLE
Release for 1.2?

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/tatsu#57]
Is there a plan to have a release of 1.2 so it can be installed through the interface rather than having to manually download and upload the files?

**Comment by stpaultim** [comment]
I've been neglecting this theme. Will review the situation this week.

**Comment by yorkshire-pudding** [comment]
@stpaultim bump

**Comment by stpaultim** [comment]
@yorkshire-pudding - Let's connect in Zulip. I'm game to create a new release, but would like to chat with you first.

**Comment by leeksoup** [comment]
Hallo, the last post was a year ago and no release 1.2 yet. Is the release going to happen still or is it abandoned? Thanks.

**Comment by Wylbur** [comment]
Let's add a list of tasks needed for a new release.  I will keep working the issue queue and add items.

**Comment by Wylbur** [comment]
Here's issues to include in the 1.2 release

- [ ] #61 
- [ ] #38 
- [ ] #63 
- [ ] #65 
- [ ] #69

**Comment by stpaultim** [comment]
Done
