### ISSUE TITLE
Missing CSS and JS Bootstrap files

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/tatsu#59]
It appears some CSS and JS Bootstrap files are being called for locally and not being found.

To reproduce:

1. Enable Tatsu and set as default theme.
2. Go to the Home page and examine the HTML in your favorite web inspector. You should see two 404 errors for:

http://mysite/themes/tatsu/css/bootstrap/bootstrap.min.css.map
http://mysite/themes/tatsu/js/bootstrap.bundle.min.js.map

Adding these files from the Bootstrap 4.3.1 repository (to match the existing bundled CSS and JS) fixes the problem.

PR to follow.

**Comment by stpaultim** [comment]
I will try to review this PR tomorrow. Thanks @bugfolder
