### ISSUE TITLE
Front page with new content type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tatsu#63]
FYI

![tatsu-cards](https://user-images.githubusercontent.com/3144571/165420247-5628d9e4-cb92-4e62-9717-099dfeec9af0.png)

**Comment by izmeez** [comment]
When 1.x-2.x is installed the three cards appears in a single column, one below the other. Not sure how to fix this.

**Comment by izmeez** [comment]
I have tried adding a file cards.css and can affect the styling of the cards but I cannot restore the default styling from .views-promoted-cards and I cannot restore the horizontal row of blocks for larger widths. I have tried:
```
@media (min-width: 48rem) {
  .view-promoted-cards .views-view-grid {
    display: inline-block;
  }
}
```
This does not work. It appears as if the display is controlled by settings elsewhere in the theme.

**Comment by izmeez** [comment]
I have made some progress and can display the cards horizontally on larger widths with the following. But, unfortunately the boxes do not stay perfectly aligned when the browser window is stretched horizontally.

```
@media (min-width: 48rem) {
  .view-promoted-cards .views-view-grid {
	margin: 1rem auto;
  }
  .view-promoted-cards .views-grid-box {
    display: inline-block;
	width: 30%;
	padding: 10px;
	border: 1px solid blue;    
  }
}
```

**Comment by Wylbur** [comment]
The Tatsu theme adds a css stylessheet named css/componenents/views.css, but this addition replaces the default views.css stylesheet from the core views module.  That file includes all the gridbox styles, which breaks the layout of the cards and other views.  

I was able to resolve this by adding the cards.css stylesheet to tatsu, and by renaming the css/componenets/views.css to css/components/views-tatsu.css.  

I'll create a pull request with this fix.

**Comment by stpaultim** [comment]
I went ahead and changed the name of views.css to views-tatsu.css on the 1.x-2.x branch.

**Comment by stpaultim** [comment]
The stacking of blocks is fixed by changing the .views css file. @izmeez and @Wylbur

**Comment by stpaultim** [comment]
The 2.x branch of Tatsu never got the cards.css that was added to Basis. I've added that into Tatsu and I think we can close this issue.
