### ISSUE TITLE
Page not found warning for themes/tatsu/images/add.png 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/tatsu#64]
Details
TYPE	page not found
DATE	Monday 7th August 2023 - 10:27
USER	
LOCATION	https://site.lndo.site/themes/tatsu/images/add.png
REFERRER	https://site.lndo.site/themes/tatsu/css/skin.css?rz0ktr
MESSAGE	themes/tatsu/images/add.png
SEVERITY	warning
HOSTNAME	172.20.0.2
OPERATIONS

**Comment by Wylbur** [comment]
I checked the skin.css file in the latest release, and there is no reference to add.png. 

Which release are you using?  Can you give more details to help resolve this?

**Comment by yorkshire-pudding** [comment]
@Wylbur - this is with the 1.2 branch

https://github.com/backdrop-contrib/tatsu/blob/179449a9a579a96f08db74259f2a696c3c263c4b/css/skin.css#L726-L729

**Comment by Wylbur** [comment]
Sorry I missed that @yorkshire-pudding I will add that to the list of fixes.  This is something that was changed in Basis since Tatsu was created.
