### ISSUE TITLE
Need to remove border bottom from first item primary menu.

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tatsu#65]
There is a 1px grey border-bottom visible on the first item in the primary menu. It appears to be related to code in css/basis-component-colors.css

`/*  components/menu-dropdown.css  */

.js .menu-dropdown li,
.js .menu-dropdown a.has-submenu.highlighted {
  border-bottom: 1px solid #bbbbbb;
}
`

It only appears on the first item "Home" and shows even when another item is selected. Removing the line appears to fix the issue.
![tatsu-primary-menu-first-element-bkgnd-bottom-edge](https://github.com/backdrop-contrib/tatsu/assets/6208775/636117af-8b69-4b04-8825-8713b8d5f9bf)

**Comment by izmeez** [comment]
Actually, removing the line 
`.js .menu-dropdown li,`
from the code below so the attribute does not apply to this element is all that's needed. However, the real cause may be elsewhere as the code below is similar to what is in the core Basis theme where this issue is not present.
`/* components/menu-dropdown.css */

.js .menu-dropdown li,
.js .menu-dropdown a.has-submenu.highlighted {
border-bottom: 1px solid #bbbbbb;
}
`

**Comment by Wylbur** [comment]
The basis-componenet-colors.css included the initial setting for a bottom border color, but in the original file, there is also a media query removing that style on large displays:
```
@media (min-width: 48em) {
  .js .menu-dropdown li,
  .js .menu-dropdown a.has-submenu.highlighted {
    border-bottom: none;
  }
}
```

We can add this additional CSS to the file to resolve this issue.
