### ISSUE TITLE
Manual install 1.x-2.x and Tatsu theme does not appear on Available Updates report

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/tatsu#66]
This may not be a specific Tatsu issue. Having installed and enable the Tatsu-1.x-2.x theme manually when going to the available updates report (/admin/reports/updates) it surprising that the theme is not listed at all.

**Comment by Wylbur** [comment]
Manually installing modules does not link them to the releases for automatic updates.  

We will release a new version, so manually installing will not be an issue.

**Comment by izmeez** [comment]
> Manually installing modules does not link them to the releases for automatic updates.

This explains some of the grief I have encountered with BD updates. There are several instances where manual install is useful and it's a shame that it is then excluded from future automatic updates.

**Comment by olafgrabienski** [comment]
What do you both mean by "manual installing"? IIRC, it's not the installation method that matters (manual installation vs. project installer) but the question if you choose an official release.

In other words, if you install a release like [1.x-1.0.5](https://github.com/backdrop-contrib/tatsu/releases/tag/1.x-1.0.5) manually, i.e. by putting it in the `modules` folder, it should be possible to update it later through the Backdrop interface.

**Comment by izmeez** [comment]
@olafgrabienski Thank you for the further clarification. I think I have added my comments to a core issue and will have to look for it. I am not referring to manual install of tagged release but manual install using the url from the code base. Nonetheless, it is a major negative to the use of the "available updates" report. In my experience that report is essential to understanding what is currently active and disabled on a site.
